// Pool of medical education topics.
// The picker below avoids repeats until the whole list is exhausted.
module.exports = [
  "Why does high blood pressure often have no symptoms?",
  "What actually happens in your body during a fever?",
  "Type 1 vs Type 2 diabetes — what's the real difference?",
  "Why antibiotics don't work on viral infections",
  "What is anemia and why does it make you tired?",
  "How does the flu vaccine actually work?",
  "Warning signs of a stroke everyone should know (FAST)",
  "What causes migraines and why are they so different from headaches?",
  "Why do we need to sleep? What happens in your brain",
  "What is inflammation and is it always bad?",
  "How kidney stones form and why they hurt so much",
  "What's actually happening during an asthma attack",
  "Why cholesterol isn't the villain you think it is",
  "What is sepsis and why is early recognition critical?",
  "How vaccines train your immune system",
  "What causes iron deficiency and who's at risk?",
  "The difference between a heart attack and cardiac arrest",
  "Why UTIs are so common and how to recognize one early",
  "What is insulin resistance?",
  "How does the body regulate blood sugar?",
  "What is a concussion and why 'just resting' isn't enough",
  "Why do allergies happen? The immune system's overreaction",
  "What is dehydration doing to your body cell by cell",
  "The link between gut health and mental health",
  "What is osteoporosis and why does bone density matter",
  "How does high cholesterol actually damage arteries?",
  "What is PCOS and why is it under-diagnosed",
  "Why does stress cause physical symptoms?",
  "What is a hernia and how does it happen",
  "Understanding thyroid disorders: hypo vs hyperthyroidism",
];
